name: Build libtorrent rasterbar builder

on:
    workflow_dispatch:

jobs:
    build:
        strategy:
            fail-fast: false
            matrix:
                arch_type: [amd64, arm64/v8, arm/v7]

        name: "${{ matrix.arch_type }}"
        runs-on: ubuntu-latest
        steps:
            -
                name: Checkout
                uses: actions/checkout@v4

            -
                name: Set Version
                id: set-version
                run: |
                    ARCH=$(echo "${{ matrix.arch_type }}" | sed 's/\///g')
                    echo "ARCH=${ARCH}"
                    echo "ARCH=${ARCH}" >> $GITHUB_OUTPUT

            -
                name: Docker meta
                id: meta
                uses: docker/metadata-action@v5
                with:
                    images: ${{ secrets.DOCKER_USERNAME }}/libtorrent-rasterbar
                    tags: |
                        type=raw,value=${{ steps.set-version.outputs.ARCH }}

            -
                name: Set Up QEMU
                uses: docker/setup-qemu-action@v3

            -
                name: Set Up Buildx
                uses: docker/setup-buildx-action@v3
                
            -
                name: Login DockerHub
                uses: docker/login-action@v3
                with:
                    username: ${{ secrets.DOCKER_USERNAME }}
                    password: ${{ secrets.DOCKER_PASSWORD }}

            -
                name: Build
                uses: docker/build-push-action@v5
                with:
                    context: libtorrent-rasterbar
                    file: libtorrent-rasterbar/Dockerfile
                    platforms: |
                        ${{ matrix.arch_type }}
                    push: true
                    tags: ${{ steps.meta.outputs.tags }}
                    labels: ${{ steps.meta.outputs.labels }}
