name: Docker readme update

on:
  workflow_dispatch:

jobs:
  job:
    name: Docker Hub Description
    runs-on: ubuntu-latest
    steps:
      - 
        name: Checkout
        uses: actions/checkout@v4

      - 
        name: Get dependency version
        id: dependency-version
        run: |
          docker run -d --name=test ddsderek/qbittorrent_skip_patch:4.3.9
          docker cp test:/usr/bin/dependency-version.json ./dependency-version.json

      -
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: 'chore(deps): update dependency version'
          branch: 4.3.9
          file_pattern: 'dependency-version.json'
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}